\input texinfo
@c -*-texinfo-*-
@c %**start of header
@settitle chez-a-sync
@setfilename chez-a-sync.info
@c %**end of header

@ifnottex
@node Top,overview,,
@top chez-a-sync reference
@end ifnottex

This is the chez-a-sync package.  It provides both an asynchronous
event loop for chez scheme, and coroutines to enable an event loop
(including other event loops) to be used with 'await' semantics to
deal with inversion of control -- otherwise known as ``callback
hell''.

@menu
General overview
* overview::       General overview of the operation of the library

Library files
* coroutines::     (a-sync coroutines) library file - provides coroutines for await semantics on asynchronous events
* event loop::     (a-sync event-loop) library file - provides an event loop for asynchronous events
* compose::        (a-sync compose) library file - provides the compose-a-sync macro interface for the a-sync coroutine
* try::            (a-sync try) library file - provides the try macro interface for dealing with exceptions
@end menu

@include overview.texi
@include coroutines.texi
@include event-loop.texi
@include compose.texi
@include try.texi

@bye
